add solution for 3-module 3-task
js-tasks-ru/nodejs-20211109_marcynuk-d pull request #4
Opened 2021-11-29 17:27 UTC by martsyniukSigma

2021-11-29 17:28 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-11-29 23:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-11-30 03:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-30 08:43 UTC, tadjik1 commented on 03-streams/03-file-server-get/server.js
> +        res.end(data);
мы не должны завершать стрим с каждым чанком. если файл будет большой (скажем 5 мегабайт), то мы преждевременно завершим запрос, не успев отдать файл целиком. посмотрите, пожалуйста, [видео](https://www.youtube.com/watch?v=vDgoDE0NucA), где я решаю именно эту задачу и объясняю подобные моменты

2021-11-30 08:44 UTC, tadjik1 requested changes
@martsyniukSigma необходимо поправить решение 3-ей задачи (про отдачу файла), задача с удалением решена верно

2021-11-30 10:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-30 11:14 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-11-30 11:50 UTC, tadjik1 approved these changes
все отлично 👍

2021-11-30 11:50 UTC, merged